server:
  port: 9004

spring:
  application:
    name: ec_shop-order-service
  cloud:
    #注册中心地址
    nacos:
      discovery:
        server-addr: 8.140.36.154:8848

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.140.36.154:3306/ec_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  #redis分布式缓存配置
  redis:
    host: 8.140.36.154
    password: 123456
    port: 8000


#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO
